//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KerningAdjuster {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KerningAdjuster.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is sample text.\nStepping Stones in the Pond\nIf you boldly go in the direction\nyou want to jump, you will leap\nautomatically.\n¥ÀîÂÄÇÈÉÊËÏÔÖÙÛÜβàáâäçèéêëïôöùûü
        /// 
        ///!
        ///&quot;
        ///#
        ///$
        ///%
        ///&amp;
        ///&apos;
        ///(
        ///)
        ///*
        ///+
        ///,
        ///-
        ///.
        ////
        ///0
        ///1
        ///2
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///:
        ///;
        ///&lt;
        ///=
        ///&gt;
        ///?
        ///@
        ///A
        ///B
        ///C
        ///D
        ///E
        ///F
        ///G
        ///H
        ///I
        ///J
        ///K
        ///L
        ///M
        ///N
        ///O
        ///P
        ///Q
        ///R
        ///S
        ///T
        ///U
        ///V
        ///W
        ///X
        ///Y
        ///Z
        ///[
        ///¥
        ///\
        ///^
        ///_
        ///`
        ///a
        ///b
        ///c
        ///d
        ///e
        ///f
        ///g
        ///h
        ///i
        ///j
        ///k
        ///l
        ///m
        ///n
        ///o
        ///p
        ///q
        ///r
        ///s
        ///t
        ///u
        ///v
        ///w
        ///x
        ///y
        ///z
        ///{
        ///|
        ///}
        ///~
        /// 
        ///À
        ///î
        ///Â
        ///Ä
        ///Ç
        ///È
        ///É
        ///Ê
        ///Ë
        ///Ï
        ///Ô
        ///Ö
        ///Ù
        ///Û
        ///Ü
        ///β
        ///à
        ///á
        ///â
        ///ä
        ///ç
        ///è
        ///é
        ///ê
        ///ë
        ///ï
        ///ô
        ///ö
        ///ù
        ///û
        ///ü
        ///(A BUTTON)
        ///(B BUTTON)
        ///(C BUTTON)
        ///(L BUTTON)
        ///(R BUTTON)
        ///(Z BUTTON)
        ///(C UP)
        ///(C DOWN)
        ///(C LEFT) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string codep {
            get {
                return ResourceManager.GetString("codep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] eng {
            get {
                object obj = ResourceManager.GetObject("eng", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
